### ISSUE TITLE
Documentation site seems to be down

### ISSUE THREAD

**Issue by zhon** [mcandre/rubycheck#8]
The website containing the documentation seems to be down: http://www.yellosoft.us/quickcheck

Can the documentation be moved to github?

**Comment by mcandre** [comment]
Oy, some (quite sparse) API docs are available at RubyDoc:

http://www.rubydoc.info/gems/rubycheck

I enjoyed Gandi.net hosting my old yellosoft virtual private linux server, but stopped patching it and I've transitioned most of the documentation for my projects into free hosts. Warning: Dork factor.

http://web.archive.org/web/20160501092737/http://www.yellosoft.us/quickcheck
