### ISSUE TITLE
Question: What are the compelling reasons to select RubyCheck vs Rantly vs Thief

### ISSUE THREAD

**Issue by zhon** [mcandre/rubycheck#9]
I am interested in property-based testing in ruby. I have done a little ``QuickCheck`` in Haskell. I am wondering why I would choose RubyCheck.

**Comment by mcandre** [comment]
If you have a choice, by all means use the original Haskell/Erlang QuickCheck libs, they offer a far richer featureset:

* Automatic test case generation based on property signatures
* Automatic failing test case simplification

rubycheck is meant for contexts where you want to use Ruby or RSpec. If you'd like to bring more features to rubycheck, or write your own, that would be cool!

https://en.wikipedia.org/wiki/QuickCheck

**Comment by zhon** [comment]
I was hoping you had written **RubyCheck** as a response to some set of features you couldn't get into **Rantly**. Implementing QuickCheck in ruby is a huge undertaking.
